use_frameworks!

platform :ios, '8.0'

target 'LLAudioQueue_Example' do
  pod 'LLAudioQueue', :path => '../'

  target 'LLAudioQueue_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
